### ISSUE TITLE
I cannot beautify my code

### ISSUE THREAD

**Issue by kamontat** [lovesegfault/beautysh#11]
It throw this error out, but i'm not sure what it mean??

```
File src/core/download_resource_management: error: indent/outdent mismatch: 2.
```

**Comment by Akumetsu-Dev** [comment]
me too, cant beautify 
File read_demo.sh: error: indent/outdent mismatch: 1.

**Comment by bemeurer** [comment]
@kamontat Can you provide me the sample file?

**Comment by kamontat** [comment]
here [link](https://pastebin.com/raw/6CfbFyH9)

**Comment by jesselang** [comment]
The code is no longer available. @kamontat can you post it here please? Otherwise there's nothing to do here.

**Comment by kamontat** [comment]
So you mean, you also don't know what this error cause?

**Comment by kamontat** [comment]
here the example code
```bash
#!/bin/bash

# -------------------------------------------------
# Description:  resource management of the download command
# List Command: check_is_resource_exist - check resource file exist
#               get_resource            - get the value in constant key
#               update_resource         - update value of resource constants in resource file
#               save_resource           - create new resource file or update if exist
# Usage:        run file in `source` command only
# Create by:    Kamontat Chantrachirathumrong
# Since:        09/09/2560 (DD/MM/YYYY)
# -------------------------------------------------
# Version:      1.0
# -------------------------------------------------
# Bug:
# -------------------------------------------------

[ -d "$NOVEL_LOCATION" ] || return 8
[ -n "$NOVEL_RESOURCE_NAME" ] || return 8

# -------------------------------------------------
# Constants
# -------------------------------------------------

# @require    - $NOVEL_LOCATION variable
#             - $NOVEL_RESOURCE_NAME variable
function get_resource_file {
    echo "$NOVEL_LOCATION"/$NOVEL_RESOURCE_NAME
}
DELIMITER="†" # alt+t

# RESOURCE_CONSTANTS
LINK_CONSTANT="Link"                   # save as string
DATE_CONSTANT="Date"                   # save as string and can convert to date
VERSION_CONSTANT="Version"             # save as string
STORY_NAME_CONSTANT="StoryName"        # save as string
FIRST_CHAPTER_CONSTANT="FirstChapter"  # save as int
LAST_CHAPTER_CONSTANT="LastChapter"    # save as int
IGNORE_CONSTANT="Ignore"               # save as boolean

DATE_FORMAT="%d%m%y%H%M%S"

# -------------------------------------------------
# Export constants
# -------------------------------------------------

declare -x DATE="$(date +$DATE_FORMAT)"

# -------------------------------------------------
# Functions
# -------------------------------------------------

# @return     - true if resource file exist, otherwise return false
function is_resource_exist {
    is_file_exist "$(get_resource_file)"
}

# @params - 1 - RESOURCE_CONSTANTS only
# @return     - value of key in resource file
function get_resource {
    local temp=$(grep -w "^$1" "$(get_resource_file)")
    IFS="$DELIMITER" read -r -a ARR <<< "$temp"
    local result=${ARR[1]}
    if [[ $1 = "$DATE_CONSTANT" ]]; then
        echo "$(date -jf "$DATE_FORMAT" "$result")"
    else
        echo "$result"
    fi
}

# @require    - $DELIMITER variable
# @params - 1 - RESOURCE_CONSTANTS only
#           2 - new value of input constant
function update_resource {
    local temp=$(grep -nw "^$1" "$(get_resource_file)")
    local line_number=${temp%%:*}
    if [[ $line_number != "" ]]; then
        sed -i -e "${line_number}s/$1.*/$1$DELIMITER$2/" "$(get_resource_file)"
        rm -f "$(get_resource_file)-e"
    else
        echo "$1$DELIMITER$2" >> "$(get_resource_file)"
    fi
}

# @require    - check_is_resource_exist function
#             - get_resource function
#             - update_resource function
#             - $DELIMITER variable
#             - $COMMAND_VERSION variable
#             - $NOVEL_LINK variable
#             - $NOVEL_NAME variable
#             - $NOVEL_START variable
#             - $NOVEL_END variable
#             - $NOVEL_IS_IGNORE variable
#             - $DATE variable
function save_resource {
    if $(is_resource_exist); then
        [[ "$(get_resource $STORY_NAME_CONSTANT)" = "" ]] && update_resource $STORY_NAME_CONSTANT $STORY_NAME                    # in case version is too old
        [[ "$(get_resource $VERSION_CONSTANT)" != "$COMMAND_VERSION" ]] && update_resource $VERSION_CONSTANT $COMMAND_VERSION    # update version (only if not equal)
        [[ $NOVEL_START -lt $(get_resource $FIRST_CHAPTER_CONSTANT) ]] && update_resource $FIRST_CHAPTER_CONSTANT $NOVEL_START   # update first chapter (only if current less than previous)
        [[ $NOVEL_END -gt $(get_resource $LAST_CHAPTER_CONSTANT) ]] && update_resource $LAST_CHAPTER_CONSTANT $NOVEL_END         # update last chapter (only if current more than previous)
        update_resource $IGNORE_CONSTANT $NOVEL_IS_IGNORE                                                                        # update to ignore this (only if ignore is 'true')
        update_resource $DATE_CONSTANT $DATE                                                                                     # update date to current
    else
        echo "$VERSION_CONSTANT$DELIMITER$COMMAND_VERSION" >> "$(get_resource_file)"
        echo "$LINK_CONSTANT$DELIMITER$NOVEL_LINK" >> "$(get_resource_file)"
        echo "$STORY_NAME_CONSTANT$DELIMITER$NOVEL_NAME" >> "$(get_resource_file)"
        echo "$FIRST_CHAPTER_CONSTANT$DELIMITER$NOVEL_START" >> "$(get_resource_file)"
        echo "$LAST_CHAPTER_CONSTANT$DELIMITER$NOVEL_END" >> "$(get_resource_file)"
        echo "$DATE_CONSTANT$DELIMITER$DATE" >> "$(get_resource_file)"
        echo "$IGNORE_CONSTANT$DELIMITER$NOVEL_IS_IGNORE" >> "$(get_resource_file)"
    fi
}
```

**Comment by kamontat** [comment]
example error 
![screen shot 2560-10-17 at 18 52 43](https://user-images.githubusercontent.com/14089557/31663461-68e52f4c-b36c-11e7-9554-34b2170448a2.png)

**Comment by bemeurer** [comment]
@kamontat I have merged @jesselang 's PR which should have a fix for this. I already have the new beautysh version on PyPI, so try updating the package and testing it again.

**Comment by kamontat** [comment]
![screen shot 2560-10-18 at 00 17 58](https://user-images.githubusercontent.com/14089557/31678944-d513dbaa-b399-11e7-9a43-235e1cc4f6b8.png)
Oh error still there...

**Comment by jesselang** [comment]
Appears to be choking here:

```
function get_resource {
    local temp=$(grep -w "^$1" "$(get_resource_file)")
```

Unclear to me what's causing the error.

**Comment by kamontat** [comment]
@jesselang oh but all syntax is correct right? 🤔

**Comment by bemeurer** [comment]
@jesselang Yeah, I've been poking at his code now for a bit and I cannot understand what's causing the error. @kamontat Check your script with [shellcheck](https://github.com/koalaman/shellcheck).

**Comment by kamontat** [comment]
First it cause this error to me so I fixes it, but the problem still going on
![screen shot 2560-10-18 at 20 14 48](https://user-images.githubusercontent.com/14089557/31720532-040a980c-b441-11e7-8c37-8209b947009f.png)

new code 

```bash
#!/bin/bash

# -------------------------------------------------
# Description:  resource management of the download command
# List Command: check_is_resource_exist - check resource file exist
#               get_resource            - get the value in constant key
#               update_resource         - update value of resource constants in resource file
#               save_resource           - create new resource file or update if exist
# Usage:        run file in `source` command only
# Create by:    Kamontat Chantrachirathumrong
# Since:        09/09/2560 (DD/MM/YYYY)
# -------------------------------------------------
# Version:      1.0
# -------------------------------------------------
# Bug:
# -------------------------------------------------

[ -d "$NOVEL_LOCATION" ] || return 8
[ -n "$NOVEL_RESOURCE_NAME" ] || return 8

# -------------------------------------------------
# Constants
# -------------------------------------------------

# @require    - $NOVEL_LOCATION variable
#             - $NOVEL_RESOURCE_NAME variable
function get_resource_file {
    echo "$NOVEL_LOCATION"/$NOVEL_RESOURCE_NAME
}
DELIMITER="†" # alt+t

# RESOURCE_CONSTANTS
LINK_CONSTANT="Link"                   # save as string
DATE_CONSTANT="Date"                   # save as string and can convert to date
VERSION_CONSTANT="Version"             # save as string
STORY_NAME_CONSTANT="StoryName"        # save as string
FIRST_CHAPTER_CONSTANT="FirstChapter"  # save as int
LAST_CHAPTER_CONSTANT="LastChapter"    # save as int
IGNORE_CONSTANT="Ignore"               # save as boolean

DATE_FORMAT="%d%m%y%H%M%S"

# -------------------------------------------------
# Export constants
# -------------------------------------------------

export DATE
DATE="$(date +$DATE_FORMAT)"

# -------------------------------------------------
# Functions
# -------------------------------------------------

# @return     - true if resource file exist, otherwise return false
function is_resource_exist {
    is_file_exist "$(get_resource_file)"
}

# @params - 1 - RESOURCE_CONSTANTS only
# @return     - value of key in resource file
function get_resource {
    local temp, result
    temp=$(grep -w "^$1" "$(get_resource_file)")
    IFS="$DELIMITER" read -r -a ARR <<< "$temp"
    result=${ARR[1]}
    if [[ $1 = "$DATE_CONSTANT" ]]; then
        date -jf "$DATE_FORMAT" "$result"
    else
        echo "$result"
    fi
}

# @require    - $DELIMITER variable
# @params - 1 - RESOURCE_CONSTANTS only
#           2 - new value of input constant
function update_resource {
    local temp=$(grep -nw "^$1" "$(get_resource_file)")
    local line_number=${temp%%:*}
    if [[ $line_number != "" ]]; then
        sed -i -e "${line_number}s/$1.*/$1$DELIMITER$2/" "$(get_resource_file)"
        rm -f "$(get_resource_file)-e"
    else
        echo "$1$DELIMITER$2" >> "$(get_resource_file)"
    fi
}

# @require    - check_is_resource_exist function
#             - get_resource function
#             - update_resource function
#             - $DELIMITER variable
#             - $COMMAND_VERSION variable
#             - $NOVEL_LINK variable
#             - $NOVEL_NAME variable
#             - $NOVEL_START variable
#             - $NOVEL_END variable
#             - $NOVEL_IS_IGNORE variable
#             - $DATE variable
function save_resource {
    if $(is_resource_exist); then
        [[ "$(get_resource $STORY_NAME_CONSTANT)" = "" ]] && update_resource $STORY_NAME_CONSTANT $STORY_NAME                    # in case version is too old
        [[ "$(get_resource $VERSION_CONSTANT)" != "$COMMAND_VERSION" ]] && update_resource $VERSION_CONSTANT $COMMAND_VERSION    # update version (only if not equal)
        [[ $NOVEL_START -lt $(get_resource $FIRST_CHAPTER_CONSTANT) ]] && update_resource $FIRST_CHAPTER_CONSTANT $NOVEL_START   # update first chapter (only if current less than previous)
        [[ $NOVEL_END -gt $(get_resource $LAST_CHAPTER_CONSTANT) ]] && update_resource $LAST_CHAPTER_CONSTANT $NOVEL_END         # update last chapter (only if current more than previous)
        update_resource $IGNORE_CONSTANT $NOVEL_IS_IGNORE                                                                        # update to ignore this (only if ignore is 'true')
        update_resource $DATE_CONSTANT $DATE                                                                                     # update date to current
    else
        echo "$VERSION_CONSTANT$DELIMITER$COMMAND_VERSION" >> "$(get_resource_file)"
        echo "$LINK_CONSTANT$DELIMITER$NOVEL_LINK" >> "$(get_resource_file)"
        echo "$STORY_NAME_CONSTANT$DELIMITER$NOVEL_NAME" >> "$(get_resource_file)"
        echo "$FIRST_CHAPTER_CONSTANT$DELIMITER$NOVEL_START" >> "$(get_resource_file)"
        echo "$LAST_CHAPTER_CONSTANT$DELIMITER$NOVEL_END" >> "$(get_resource_file)"
        echo "$DATE_CONSTANT$DELIMITER$DATE" >> "$(get_resource_file)"
        echo "$IGNORE_CONSTANT$DELIMITER$NOVEL_IS_IGNORE" >> "$(get_resource_file)"
    fi
}
```

**Comment by kamontat** [comment]
Here is final code that I fixes all code error warning and suggestion.

```bash
#!/bin/bash

# -------------------------------------------------
# Description:  resource management of the download command
# List Command: check_is_resource_exist - check resource file exist
#               get_resource            - get the value in constant key
#               update_resource         - update value of resource constants in resource file
#               save_resource           - create new resource file or update if exist
# Usage:        run file in `source` command only
# Create by:    Kamontat Chantrachirathumrong
# Since:        09/09/2560 (DD/MM/YYYY)
# -------------------------------------------------
# Version:      1.0
# -------------------------------------------------
# Bug:
# -------------------------------------------------

[ -d "$NOVEL_LOCATION" ] || return 8
[ -n "$NOVEL_RESOURCE_NAME" ] || return 8

# -------------------------------------------------
# Constants
# -------------------------------------------------

# @require    - $NOVEL_LOCATION variable
#             - $NOVEL_RESOURCE_NAME variable
function get_resource_file {
    echo "$NOVEL_LOCATION"/"$NOVEL_RESOURCE_NAME"
}
DELIMITER="†" # alt+t

# RESOURCE_CONSTANTS
LINK_CONSTANT="Link"                   # save as string
DATE_CONSTANT="Date"                   # save as string and can convert to date
VERSION_CONSTANT="Version"             # save as string
STORY_NAME_CONSTANT="StoryName"        # save as string
FIRST_CHAPTER_CONSTANT="FirstChapter"  # save as int
LAST_CHAPTER_CONSTANT="LastChapter"    # save as int
IGNORE_CONSTANT="Ignore"               # save as boolean

DATE_FORMAT="%d%m%y%H%M%S"

# -------------------------------------------------
# Export constants
# -------------------------------------------------

export DATE
DATE="$(date +$DATE_FORMAT)"

# -------------------------------------------------
# Functions
# -------------------------------------------------

# @return     - true if resource file exist, otherwise return false
function is_resource_exist {
    is_file_exist "$(get_resource_file)"
}

# @params - 1 - RESOURCE_CONSTANTS only
# @return     - value of key in resource file
function get_resource {
    local temp, result
    temp=$(grep -w "^$1" "$(get_resource_file)")
    IFS="$DELIMITER" read -r -a ARR <<< "$temp"
    result=${ARR[1]}
    if [[ $1 = "$DATE_CONSTANT" ]]; then
        date -jf "$DATE_FORMAT" "$result"
    else
        echo "$result"
    fi
}

# @require    - $DELIMITER variable
# @params - 1 - RESOURCE_CONSTANTS only
#           2 - new value of input constant
function update_resource {
    local temp, line_number

    temp=$(grep -nw "^$1" "$(get_resource_file)")
    line_number=${temp%%:*}
    if [[ $line_number != "" ]]; then
        sed -i -e "${line_number}s/$1.*/$1$DELIMITER$2/" "$(get_resource_file)"
        rm -f "$(get_resource_file)-e"
    else
        echo "$1$DELIMITER$2" >> "$(get_resource_file)"
    fi
}

# @require    - check_is_resource_exist function
#             - get_resource function
#             - update_resource function
#             - $DELIMITER variable
#             - $COMMAND_VERSION variable
#             - $NOVEL_LINK variable
#             - $NOVEL_NAME variable
#             - $NOVEL_START variable
#             - $NOVEL_END variable
#             - $NOVEL_IS_IGNORE variable
#             - $DATE variable
function save_resource {
    if is_resource_exist; then
        [[ "$(get_resource $STORY_NAME_CONSTANT)" = "" ]] && update_resource $STORY_NAME_CONSTANT "$STORY_NAME"                    # in case version is too old
        [[ "$(get_resource $VERSION_CONSTANT)" != "$COMMAND_VERSION" ]] && update_resource $VERSION_CONSTANT "$COMMAND_VERSION"    # update version (only if not equal)
        [[ $NOVEL_START -lt $(get_resource $FIRST_CHAPTER_CONSTANT) ]] && update_resource $FIRST_CHAPTER_CONSTANT "$NOVEL_START"   # update first chapter (only if current less than previous)
        [[ $NOVEL_END -gt $(get_resource $LAST_CHAPTER_CONSTANT) ]] && update_resource $LAST_CHAPTER_CONSTANT "$NOVEL_END"         # update last chapter (only if current more than previous)
        update_resource $IGNORE_CONSTANT "$NOVEL_IS_IGNORE"                                                                        # update to ignore this (only if ignore is 'true')
        update_resource $DATE_CONSTANT "$DATE"                                                                                     # update date to current
    else
      {
        echo "$VERSION_CONSTANT$DELIMITER$COMMAND_VERSION"
        echo "$LINK_CONSTANT$DELIMITER$NOVEL_LINK"
        echo "$STORY_NAME_CONSTANT$DELIMITER$NOVEL_NAME"
        echo "$FIRST_CHAPTER_CONSTANT$DELIMITER$NOVEL_START"
        echo "$LAST_CHAPTER_CONSTANT$DELIMITER$NOVEL_END"
        echo "$DATE_CONSTANT$DELIMITER$DATE"
        echo "$IGNORE_CONSTANT$DELIMITER$NOVEL_IS_IGNORE"
      } >> "$(get_resource_file)"
    fi
}
```

**Comment by zone01-org** [comment]
in my code it fails to process lines with `<<<`

**Comment by bemeurer** [comment]
This should now be fixed. @zone01-org Can you confirm the latest version solves this?

**Comment by rkennedy** [comment]
The current master branch exhibits the reported behavior on the code submitted by kamontat on October 18. Commit 9e98979087f0923ae222770d80fb25728c6914c2 doesn't fix it. Here's a smaller example that exhibits the same behavior:

```bash
#!/bin/bash

function get_resource {
    IFS="$DELIMITER" read -r -a ARR <<< "$temp"
}
```

The problem is indeed the `<<<` here-string syntax. Beautysh mostly assumes that any appearance of `<<` indicates a here document, which is false. The above commit changed beautysh to exclude a very specific use of here strings (i.e., the ones at the ends of `while` loops), but doesn't address broader use of here strings. (Several examples available in the [Advanced Bash-Scripting Guide on the topic](https://www.tldp.org/LDP/abs/html/x17837.html).)

**Comment by Lin-Buo-Ren** [comment]
I encounter this issue as well, which is also reproduced with bashbeautify, which seems to have similar codebase: https://github.com/bergwerf/bashbeautify/issues/12

**Comment by ApoXalvation** [comment]
Same here:
`#!/bin/bash
if true; then
  OUTPUT=$OUTPUT"\033[0;33mINTERFACES\033[0m\n"
fi`

**Comment by Abasz** [comment]
Hi, I still have some problems with here string formatting in beautybash:

```shell
function install() {
    echo "Certificate is ready, downloading..."
    CERTIFICATES=$(curl api.zerossl.com/certificates/"$ID"/download/return?access_key="$ACCESS_KEY")

    echo "Installing new certificates"
    jq -r '.["certificate.crt"]' <<< "$CERTIFICATES" > "$APACHE_CONF_DIR/ssl/test.cert"
       jq -r '.["ca_bundle.crt"]' <<< "$CERTIFICATES" > "$APACHE_CONF_DIR/ssl/test_boundle.cert"
}
```

this would give an error: Couldn't format the document:File (stdin): error: indent/outdent mismatch: 1.

if I change the lines with the here string to be in double quotes `"jq -r '.[\"certificate.crt\"]' <<< $CERTIFICATES)"` formatting works fine.

**Comment by abrahammurciano** [comment]
I am still getting this error. Here is my code, which runs fine.

```bash
#!/usr/bin/env bash

# Program which will capitalize the first letter of all sentences in all files in the directory txt.

for file in txt/*; do
    # replaced=$(< "$file" tr '\n' '\r' | sed -Ee "s/(^|[.?!]['\"“)\]’]?\s+)(['‘\"”(\[]?)([a-z])/\1\2\U\3/g" | tr '\r' '\n')
    replaced=$(< "$file" tr '\n' '\r' | sed -Ee "s/(^|[.?!]\s+)(['‘\"(\[]?)([a-z])/\1\2\U\3/g" | tr '\r' '\n')
    echo "$replaced" > "$file"
done

```
